### ISSUE TITLE
Фильтрация по цене и производителю?

### ISSUE THREAD

**Issue by gitrequests** [dvizh/shop-skeleton#16]
yii2-filter не решает эту задачу, т.к. работает с отдельной таблицей, поэтому отпишу сюда. Раз это скелетон приложения неплохо было бы видеть такой нужный функционал из коробки.

**Comment by pistol88** [comment]
Через неделю - две на скелетоне будет живой сайт, там будет весь функционал. Пока что вот пример фильтрации по цене:

```        
if($sort = Yii::$app->request->get('sort')) {
            $productsFind = $productsFind->joinWith(['prices']);

            if($sort == 'expensive') {
                $productsFind = $productsFind->orderBy('{{%shop_price%}}.price DESC');
            } else {
                $productsFind = $productsFind->orderBy('{{%shop_price%}}.price ASC');
            }
        }
```

**Comment by gitrequests** [comment]
У вас же пример сортировки а не фильтрации...

**Comment by pistol88** [comment]
Вместо orderBy поставить andWhere ;)

**Comment by gitrequests** [comment]
Мужики, что там с живым сайтом? Или уже не ждем?

**Comment by pistol88** [comment]
Он готов в целом, осталось тысяча мелочей.... Все руки не доходят, спасибо за пинок - еще поработаю на выходных ;)

**Comment by pistol88** [comment]
Еще маленький шажок сделали http://dss.dvizh.net/
https://github.com/nn250495/dss
Сейчас осталось выпилить косяки и наполнить контентом.

**Comment by gitrequests** [comment]
Зачетный фронт запилили!
